### ISSUE TITLE
Télécommande générale virtuelle

### ISSUE THREAD

**Issue by pinton40** [javicalle/rts_rflink#1]
Bonjour,
 je rencontre un problème avec ma télécommande générale virtuelle sur home assistant qui me permet de fermer tous les volets à la tombée de la nuit j'ai pourtant mis dans aliases son adresse RTS Mais cela ne met pas à jour la position des volets. Pouvez vous m'aider ? 

```yaml 
# Rflink
rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_8573332373935111A030-if00
  #wait_for_ack: false

cover:
  - platform: rflink
    devices:
      RTS_FF0101_0:
        name: "volet_Telecommande_generale"
        aliases:
          - rts_349e48_01 # telecommmande generale Somfy smove
  - platform: rts_rflink
  
    devices:
      RTS_010201_0:
        name: "volet_cuisine"
        rts_my_position: 0
        travelling_time_down: 26
        travelling_time_up: 26
        aliases:
          - rts_2d8148_01 # telecommande cuisine Somfy smove
          - rts_349e48_01 # telecommmande generale Somfy smove
          - RTS_FF0101_0  # telecommmande generale HA
      RTS_020101_0:
        name: "volet_Salle_a_manger"
        rts_my_position: 14
        travelling_time_down: 24
        travelling_time_up: 24
        aliases:
          - rts_a8d747_01 # telecommande salle a manger Somfy smove
          - rts_349e48_01 # telecommmande generale Somfy smove
          - RTS_FF0101_0 # telecommmande generale HA
```

Merci
